---
header-includes:
  - \usepackage{graphicx}
  - \usepackage{float}
  - \usepackage{caption} 
  - \captionsetup[figure]{skip=10pt}
output: 
  pdf_document:
    number_sections: false
    # citation_package: natbib
    keep_tex: true
    fig_caption: true
    # latex_engine: pdflatex
    # template: ~/switchdrive/config/Rmarkdown/svm-latex-ms.tex
title: "Data-generating process assumed by the Beta-Binomial by Annotator model"
author:
- name: Hauke Licht
  affiliation: "Department of Political Science, University of Zürich"
# date: "`r format(Sys.time(), '%B %d, %Y')`"
# geometry: margin=3in
citecolor: black
urlcolor: black
linkcolor: black
# fontfamily: mathpazo
fontsize: 12pt
spacing: onehalf
bibliography: /Users/licht/switchdrive/Documents/work/phd/phd_research.bib
biblio-style: apsr
---

```{r knitr, echo = FALSE}
knitr::opts_chunk$set(
  echo = FALSE
  , warning = FALSE
  , message = FALSE
  , fig.align = 'center'
  , fig.height = 3
  , fig.width = 6
  , fig.pos = "H"
)
```

```{r setup}
options(digits = 3)

# set the file path
file_path <- file.path("~", "switchdrive", "Documents", "work", "phd", "methods", "crowd-sourced_annotation")

# load required namespaces

library(dplyr)
library(functional)
library(purrr)
library(tidyr)
library(stringr)
library(ggplot2)
library(ggridges)
library(grid)
library(gridExtra)
library(gtable)
library(extrafont)
# loadfonts(device = "win")

theme_set(
  theme_bw() +
    theme(
      legend.position = "bottom"
      # Roman font: see https://medium.com/@fulowa/latex-font-in-a-ggplot-9120caaa5250
      , text = element_text(size=10, family="LM Roman 10")
      , axis.text = element_text(size=10, family="LM Roman 10")
      , panel.grid = element_blank()
      , panel.border = element_blank()
      , plot.title = element_text(hjust = .5)
      , plot.subtitle = element_text(hjust = .5)
      , axis.title.y = element_text(angle = 0, vjust = .5)
    )
)
```


```{r thetas_ae_scatter, fig.height=2, fig.width=5, fig.cap="Mean posterior estimates of coders' abilities for elite critique classification. $\\theta_0$ and $\\theta_1$ refer to specificity  and sensitivity, respectively."}

set.seed(1234)

pdf_pi <- function(x) dbeta(x, 2, 8)
pdf_theta0 <- function(x) dbeta(x, 12, 2)
pdf_theta1 <- function(x) dbeta(x, 9, 3)

seq1000 <- Curry(seq, length.out = 1000L)

p_pi_pdf <- ggplot(tibble(x = seq1000(0, 1)), aes(x)) + 
  geom_area(stat = "function", fun = pdf_pi, fill = "grey", alpha = .75) + 
  stat_function(fun = pdf_pi) + 
  scale_y_continuous(breaks = NULL) +
  labs(
    title = "Prevalence of positive instances" 
    , x = expression(pi%~%B*e*t*a(2,~8))
    , y = NULL
  ) 

p_c_pd <- tibble(count = c(1, 4), class = c("pos", "neg")) %>% 
  ggplot(aes(x = 1, y = count, fill = class)) + 
    geom_bar(
      color = "black"
      , position = "fill"
      , stat = "identity"
      , alpha = .75
      , show.legend = FALSE
      , width = .3
    ) +
    geom_text(
      mapping = aes(x = 1, y = 0.5/5)
      , label = expression(c[i]==1)
      , vjust = "center"
      , hjust = "center"
      , size = 3
      , na.rm = TRUE
    ) +
    geom_text(
      mapping = aes(x = 1, y = 1/5+2/5)
      , label = expression(c[i]==0)
      , vjust = "center"
      , hjust = "center"
      , size = 3
      , na.rm = TRUE
    ) +
    coord_flip() +
    scale_x_continuous(breaks = NULL) + 
    scale_fill_manual(values = c(neg = "darkgrey", pos = "white")) + 
    labs(
      title = expression(paste("Instance ",italic(i),"'s true label"))
      , y = expression(c[i]%~%B*e*r*n*o*u*l*l*i(pi))
      , x = NULL
    )

p_sens_pdf <- ggplot(tibble(x = seq1000(0, 1)), aes(x)) + 
  geom_area(stat = "function", fun = pdf_theta1, fill = "grey", alpha = .75) + 
  stat_function(fun = pdf_theta1) + 
  scale_y_continuous(lim = c(0,5), position = "right", breaks = NULL) +
  labs(
    title = expression(paste("Coder ",italic(j),"'s sensitivity"))
    , x = expression(theta[1*j]%~%B*e*t*a(9,3))
    , y = NULL
  ) 

p_spec_pdf <- ggplot(tibble(x = seq1000(0, 1)), aes(x)) + 
  geom_area(stat = "function", fun = pdf_theta0, fill = "grey", alpha = .75) +
  stat_function(fun = pdf_theta0) +
  scale_y_continuous(lim = c(0,5), breaks = NULL) +
  labs(
    title = expression(paste("Coder ", italic(j), "'s specificity"))
    , x = expression(theta[0*j]%~%B*e*t*a(12,2))
    , y = NULL
  ) 

p_c1_pd <- tibble(count = c(9, 3), class = c("pos", "neg")) %>% 
  ggplot(aes(x = 1, y = count, fill = class)) + 
    geom_bar(
      color = "black"
      , position = "fill"
      , stat = "identity"
      , alpha = .75
      , show.legend = FALSE
    ) +
    geom_text(
      mapping = aes(x = 1, y = 4.5/12)
      , label = expression(y[i*j]==1)
      , vjust = "center"
      , hjust = "center"
      , size = 3
      , na.rm = TRUE
    ) +
    geom_text(
      mapping = aes(x = 1, y = 9/12+1.5/12)
      , label = expression(y[i*j]==0)
      , vjust = "center"
      , hjust = "center"
      , size = 3
      , na.rm = TRUE
    ) +
    coord_flip() +
    scale_x_continuous(breaks = NULL) + 
    scale_fill_manual(values = c(neg = "darkgrey", pos = "white")) +
    labs(
      title = expression(paste("Coder ", italic(j), "'s judgment of instance ", italic(i)))
      , x = NULL
      , y = expression(y[i*j]%~%B*e*r*n*o*u*l*l*i(y[i*j]%*%theta[1*j]))
    )

p_c0_pd <- tibble(count = c(2, 12), class = c("pos", "neg")) %>% 
  ggplot(aes(x = 1, y = count, fill = class)) + 
    geom_bar(
      color = "black"
      , position = "fill"
      , stat = "identity"
      , alpha = .75
      , show.legend = FALSE
    ) +
    geom_text(
      mapping = aes(x = 1, y = 1/12)
      , label = expression(y[i*j]==1)
      , vjust = "center"
      , hjust = "center"
      , size = 3
      , na.rm = TRUE
    ) +
    geom_text(
      mapping = aes(x = 1, y = 2/12+5/12)
      , label = expression(y[i*j]==0)
      , vjust = "center"
      , hjust = "center"
      , size = 3
      , na.rm = TRUE
    ) +
    coord_flip() +
    scale_x_continuous(breaks = NULL) + 
    scale_fill_manual(values = c(neg = "darkgrey", pos = "white")) +
    labs(
      title = expression(paste("Coder ",italic(j),"'s judgment of instance ",italic(i)))
      , x = NULL
      , y = expression(y[i*j]%~%B*e*r*n*o*u*l*l*i*((1-c[i])%*%(1-theta[0*j])))
    )

ws <- grid::rectGrob(gp = grid::gpar(fill = NA, col = NA) )

g_pi_pdf <- ggplot2::ggplotGrob(p_pi_pdf)
g_c_pd <- ggplot2::ggplotGrob(p_c_pd)

g_c_pd$widths <- g_pi_pdf$widths
# g_c_pd$heights[c(3, 9, 10)] <- unit(.5, "grobheight", g_c_pd)


g_spec_pdf <- ggplot2::ggplotGrob(p_spec_pdf)
g_c0_pd <- ggplot2::ggplotGrob(p_c0_pd)
g_spec_pdf$widths <- g_c0_pd$widths

g_sens_pdf <- ggplot2::ggplotGrob(p_sens_pdf)
g_c1_pd <- ggplot2::ggplotGrob(p_c1_pd)
g_sens_pdf$widths <- g_c1_pd$widths

pi_determines <- textGrob(
  expression(paste(pi, " determines how probable ", c[i]==1))
  # , x = unit(1, "in")
  # , y = unit(0, "in")
  , vjust = 0.5
  , gp = gpar(fontfamily = "LM Roman 10")
)

c_is_1 <- textGrob(
  expression(paste("given ", c[i]==1))
  # , x = unit(1, "in")
  # , y = unit(0, "in")
  , vjust = 1
  , gp = gpar(fontfamily = "LM Roman 10")
)

c_is_0 <- textGrob(
  expression(paste("given ", c[i]==0))
  # , x = unit(1, "in")
  # , y = unit(0, "in")
  , vjust = 1
  , gp = gpar(fontfamily = "LM Roman 10")
)

spec_determines <- textGrob(
  expression(paste(theta[0*j], " determines how probable ", y[i*j]==0))
  , vjust = 0.5
  , gp = gpar(fontfamily = "LM Roman 10")
)

sens_determines <- textGrob(
  expression(paste(theta[1*j], " determines how probable ", y[i*j]==1))
  , vjust = 0.5
  , gp = gpar(fontfamily = "LM Roman 10")
)

g <- gtable::gtable_matrix(
  name = "demo"
  , grobs = matrix(
    list(
      ws, ws, g_pi_pdf, ws, ws,
      ws, ws, pi_determines, ws, ws,
      g_sens_pdf, c_is_1, g_c_pd, c_is_0, g_spec_pdf,
      sens_determines, ws, ws, ws, spec_determines, 
      g_c1_pd, ws, ws, ws, g_c0_pd
    )
    , ncol = 5
    , byrow = TRUE
  )
  , widths = grid::unit(c(3, 1, 4, 1, 3), "in") 
  , heights = grid::unit(c(2, .3, 2, .3, 1.6), "in")
)
```

```{r, fig.width=7, fig.height=4, eval = FALSE}
plot(g)
```

```{r bba_illustration, fig.width=12, fig.height=8}
grid.newpage()
grid.draw(g)
```




```{r bba_pi_and_c, fig.width=4, fig.height=4.5}
g2 <- gtable::gtable_matrix(
  name = "demo"
  , grobs = matrix(list(g_pi_pdf, pi_determines, g_c_pd)
    , ncol = 1
    , byrow = TRUE
  )
  , widths = grid::unit(c(4), "in") 
  , heights = grid::unit(c(2, .5, 1.2), "in")
)

grid.newpage()
grid.draw(g2)

```


```{r bba_sens_and_spec, fig.width=6.1, fig.height=4.2}
g3 <- gtable::gtable_matrix(
  name = "foo"  
  , grobs = matrix(
    list(
      c_is_1, ws, c_is_0,
      g_sens_pdf, ws, g_spec_pdf,
      sens_determines, ws, spec_determines, 
      g_c1_pd, ws, g_c0_pd
    )
    , ncol = 3
    , byrow = TRUE
  )
  , widths = grid::unit(c(2.9, .3, 2.9), "in") 
  , heights = grid::unit(c(.5, 2, .5, 1.2), "in")
)

grid.newpage()
grid.draw(g3)

```


